package com.soft.primerproyecto.Entidades;
// Generated 23/01/2016 09:36:45 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="sucursal"
    ,catalog="universidad"
)
public class Sucursal  implements java.io.Serializable {


     private Integer idSucursal;
     private String nombre;
     private String direccion;
     private int telefono;

    public Sucursal() {
    }

    public Sucursal(String nombre, String direccion, int telefono) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_sucursal", unique=true, nullable=false)
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }

    
    @Column(name="nombre", nullable=false, length=65535)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", nullable=false, length=65535)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false)
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }




}


